version: 2.1

orbs: 
    python: circleci/python@2.0.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - run: 
          command: |
            pip install requests
            requests --junitxml=test-results/junit.xml TestGitHubAp.py
      - store_test_results:
          path: test-results
workflows:
  testing_GitHubApi:
    jobs:
      - build-and-test
